version: '3'
services:
  workspace:
    build: .
    container_name: sparring-workspace
    stdin_open: true
    volumes:
      - .:/sparring-workspace
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: sparring-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./init_db/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./init_db/99_installer.sh:/docker-entrypoint-initdb.d/99_installer.sh
      - ./init_db/world.sql.gz:/docker-entrypoint-initdb.d/world.sql.gz
    ports:
      - 3307:3306
